spring.application.name=hostRifas


spring.datasource.url = jdbc:mysql://localhost:3306/hostrifa
spring.datasource.username = root
spring.datasource.password = 
spring.jpa.hibernate.ddl-auto = update


upload.dir=uploads